### ISSUE TITLE
Appendix P - update and fix

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PCF#1]
Import and improve Appendix P

Improvements from CP-ITI-948 from @ElliotSilver 
    https://docs.google.com/document/d/1vT9YVA0JiBm2K8JeYf4CZKNY4ss6DpgX/edit#heading=h.30j0zll

Plus update to FHIR Consent, and anything

**Comment by JohnMoehrke** [comment]
@mojitoj would this page be a good place for the concepts in your latest blog?
  https://jafarim.net/consent-overarching-policy/

Note that the current text is historic, it exists in ITI Technical Framework - Volume 1 - as Appendix P -- https://profiles.ihe.net/ITI/TF/Volume1/ch-P.html

We will be updating it in whatever way we need to. It will still be informative, and it will still be mostly about the original scope of policy, how to create them, what they need to cover, and how one might process them. There is some edits identified by Elliot Silver. I think your blog does a fantastic job.

**Comment by mojitoj** [comment]
Thanks John. If we are creating an inventory of existing literature on consent, there are also a number of blog posts from the LEAP project here: https://sdhealthconnect.github.io/leap/posts.html

**Comment by mojitoj** [comment]
I can create a PR for that.

**Comment by mojitoj** [comment]
https://github.com/IHE/ITI.PCF/pull/2
