### ISSUE TITLE
[Bug]: Authorized User Should Be An Intermediate Option

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#10]
### Contact Details

slagesse@epic.com

### Section Number

53.2.2 Explicit Basic Option

### What is wrong

The Explicit Basic Option states that the agent accessing the data is one parameter that may be used under this option. Many trust domains today do not have such a provision; they allow access by way of being a member of the trust domain. 

For this reason, implementations will want to be able to support the other aspects of Explicit Basic without concern for who has access. 

### Describe the solution you'd like

Make this an Intermediate option. 

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
make this an open issue.

**Comment by JohnMoehrke** [comment]
created open issue PCF_19 (issue #19)
