### ISSUE TITLE
[Bug]: Do Not Require Specific Sensitivity Code ValueSet

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#13]
### Contact Details

slagesse@epic.com

### Section Number

53.4.2.7 Advanced Consent Content

### What is wrong

Section 53.4.2.7 Advanced Consent Content defines a set of "stigmatizing sensitive classifications" and states they shall be supported. 

These are going to be highly dependent on trust domain policy and a technical specification should not attempt to enumerate them. Different global jurisdictions will have very different ideas of what a reasonable ValueSet should and should not include. 

### Describe the solution you'd like

Require support for a configurable ValueSet and point to the current list as an example. 

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
Make open issue asking about sensitivity classes that would be minimally required. Pointing out that there is likely no minimal set that is universally globally required. With the expectation that TI would not be the current list, but some smaller list of sensitivity classifications, or no required sensitivity classifications. Should the sensitivity classifications that are moved out of the mandatory requirement still listed as a useful mention?

**Comment by JohnMoehrke** [comment]
created issue #18
