### ISSUE TITLE
[Bug]: Questions About ihe_pcf extension

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#14]
### Contact Details

slagesse@epic.com

### Section Number

Updates to ITI-71

### What is wrong

Two questions about the content of the ihe_pcf extension:

- Is patient_id needed when it is already present in the ihe_iua extension?
- Should the doc_id parameter be an array?

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
make clear doc_id and acp are arrays. Clarify that acp tends to come from Consent.policy.uri.
