### ISSUE TITLE
[Bug]: Use Case Descriptions Read Poorly

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#16]
### Contact Details

slagesse@epic.com

### Section Number

53.4.2.1.1
53.4.2.2.1
53.4.2.3.1

### What is wrong

The use case descriptions do not flow well in paragraph form. Based on the format of the markdown, I am not sure if these were intended to be expressed in paragraph form, or some other format. 

Example:  Given an Organization controlling some Patient identifiable Data And they have written and published Patient Privacy Policies And there is no consent on file for a given Patient When they present their Patient Privacy Policies to a given Patient And the Patient either agrees, disagrees, or adds acceptable parameters Then a Consent is captured by the Consent Recorder actor and stored in the Consent Registry

### Describe the solution you'd like

Either reformat for rephrase as prose. 

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
make cucumber look proper
