### ISSUE TITLE
[Bug]: Consent Registry does not make audit decisions and so cannot record the Consent Authorication Decision Audit Message

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#27]
### Contact Details

slagesse@epic.com

### Section Number

1:53.3.1

### What is wrong

This section requires the Consent Registry to record the Consent Authorization Decision Audit Message, but the Consent Registry simply stores the Consent Resources, it does not make decisions. 

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
agreed. Will fix. That AuditEvent would be for the Consent Authorization Server.
