### ISSUE TITLE
[Bug]: Consent Resource Profiles Overly Restrictive

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#28]
### Contact Details

slagesse@epic.com

### Section Number

All Consent Profiles

### What is wrong

Consent.policy.authority and Consent.policyRule are forbidden. Based on my reading of the description of those fields, they could be included for informational purposes with no expectations on the Consent Enforcer to process them. Therefore, forbidding them is more restrictive than necessary, and it would be better to simply not profile those elements. 

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
They are forbidden in PCF as PCF has no use for them. It is certainly possible to populate them, but that population would be use beyond that defined in PCF and thus would be not compliant with PCF.

leaving them optional without a use-case for their use seems not appropriate. However we could define that they are optional, and would be used for some specific meaning. I think we would need some defined meaning with some defined examples.

That said, we could use one of the new replacements for must-support, such as `no-error`, `can-ignore`. This does not seem useful.

**Comment by slagesse-epic** [comment]
I don't see a reason why we need to do anything at all with them. If they are not constrained, then they fall under the base FHIR definition. Which is to say they do not play a role in PCF, but might play a role in other implementation details happening in parallel to PCF. 

Forbidding the population of these elements makes support for PCF harder, because it means that a system that wants to populate these cannot be compliant with PCF while populating them. On the other hand, I don't see what problem allowing them would pose, since an actor just doing PCF would ignore them, and and they are not considered modifier elements and so can be safely ignored according to the base FHIR specification.

**Comment by JohnMoehrke** [comment]
agree to allow. explain that the decision actor can ignore.
