### ISSUE TITLE
[Bug]: Multiple Examples With Same Name

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#29]
### Contact Details

slagesse@epic.com

### What is wrong

There are 2 examples entitled "Consent for treatment example" and multiple examples entitled "Consent allowing NORMAL and RESTRICTED access". This makes it difficult to understand the differences between and meaning of those examples. 

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
will make better titles and descriptions.
