### ISSUE TITLE
[Bug]: More Guidance Update Consent

### ISSUE THREAD

**Issue by mojitoj** [IHE/ITI.PCF#32]
### Section Number

1:53.4.2.2 Use Case #2: Update Existing Consent

### What is wrong

I think we need at least some discussion on to provide more guidance around this use case. Consents are generally not simply 'updated'; the consent is usually an executed signed contract that cannot be simply modified. I think updating a consent means revoking the old one and filing a new one with the updated rules. 
There are some requirements and alternatives here:
- We can say that all that stuff is 'ceremony' and out of scope and we only cover the case of an update to the consent once the paperwork is settled in the ceremony section. This is one alternative but we still need to be able to track how the consent has been updated (through Provenance) to ensure we record: when the updated consent came into effect, who did the update, and a link to the paperwork/ceremony artifacts that memorializes the update.
- Alternatively, we can say that we don't update the consent. We mark the old consent as 'inactive' and create a new consent with updated rules. Still, I think we need to trace back both the old and the new consent back to the paperwork and ceremony artifacts.

### Describe the solution you'd like

I already mentioned two alternatives but I lean towards the second alternative because I think it is important that we leave a record of the old consent --to which audit events and old consent decisions may be linked-- in order to have a more consistent record. 

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
a good illustrative use-case is where past Consent is on paper, as is the new Consent on paper. Clearly the paper is not being revised, it is literally a new piece of paper.  So, this could be implemented in one of two ways:
1. Revise the existing FHIR Consent instance --> Update
2. Add a new FHIR Consent with the new details (new), and (update) the old to mark as terminated.
3. Add a new FHIR Consent with the new details (new), and (delete) the old

**Comment by mojitoj** [comment]
I am not happy about (3) because it may break references to audit logs that memorialize consent decisions made based on that consent. I think it makes more sense to preserve the historical consents as 'inactive' to make sure accounting can be tracked as to what was authorized based on what consent.

**Comment by mojitoj** [comment]
By the same token I prefer (2) over (1) because it allows a more tangible reflection of what happened outside the electronic consent (wtr to ceremony) and also allow the old consent to remain reachable as its own entity with its status reflecting precisely what happens to it. 
I am generally more in favor of keeping the consent resource close to the consent as it was signed and executed in the ceremony.

**Comment by JohnMoehrke** [comment]
I am not sure we have a clear "Interoperability" choice, so we may choose to just identify these alternatives as systems-engineering choices to be made beyond the scope of PCF.
