### ISSUE TITLE
[Bug]: Require Consent Registries To Support actor Search Parameter

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#35]
### Contact Details

slagesse@epic.com

### Section Number

2:3.108.4.1.2.1

### What is wrong

Consent registries are required to support the patient, patient.identifier, and status search parameters. It would be common to also want to specify the actor search parameter, for example, to search on cases where the requestor is the information recipient. 

An even better version of this requirement would be to allow searching on combinations of provision.actor.role and provision.actor.reference as a composite search parameter, ie, for searching for cases where actor A is the information recipient and actor B is the custodian. 

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
I added actor search parameter. I do not understand how to address the second paragraph.
