### ISSUE TITLE
[Bug]: Confusing Language in Opening Paragraph

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#5]
### Contact Details

slagesse@epic.com

### Section Number

53

### What is wrong

The last sentence of the first paragraph is confusing me. I am not able to figure out what it is trying to say. 

" For example a user that would never be allowed access, would have been denied access at the IUA level, but the identity properties provided by the IUA are input to the privacy authorization decision that is the focus of PCF."

### Describe the solution you'd like

Please rephrase to be more clear. 

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
fix
