### ISSUE TITLE
[Bug]: IUA Optional Options Should Not Be Required

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#6]
### Contact Details

slagesse@epic.com

### Section Number

Table 53.1-2 - IUA Profile - Actors and Transactions

### What is wrong

The Get Authorization Server metadata option in IUA is optional. I do not see a compelling reason why it should be required in PCF. 

For the Introspect Token option, it is useful for this to be optional to handle the case where the Authorization Server and Resource Server are grouped. In this case, ITI-102 will not be supported because this transaction will happen using internal mechanisms. 

### Describe the solution you'd like

Return both of these options to be optional. 

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
fix.

Note 1: Authorization Server or Resource Server Actors shall support at least one of the following options: JWT Token, or Token Introspection.
