### ISSUE TITLE
[Bug]: Unclear How To Implement Break-Glass Policy

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#7]
### Contact Details

slagesse@epic.com

### Section Number

53.2.1 Implicit Option

### What is wrong

The Implicit Option states that compliant systems must support the https://profiles.ihe.net/ITI/PCF/Policy-break-glass-only policy. However, the IG does not describe how break-glass would be implemented. Thus, it is unclear what a Consent Enforcer would need to do to comply with this requirement. 

### Describe the solution you'd like

Remove the requirement to support break-glass or specify what it means to support break-glass. 

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
open issue. ask if it is useful to keep the PCF break-glass given that there is no clear way for break-glass to be declared or to learn that break-glass would be useful to a given user that is authorized to declare break-glass.

**Comment by JohnMoehrke** [comment]
made open issue PCF_20 (Issue #20)
