### ISSUE TITLE
[Bug]: What is the purpose of the Implicit Option in the Consent Recorder

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PCF#9]
### Contact Details

slagesse@epic.com

### Section Number

53.2 - PCF Actor Options

### What is wrong

The Implicit Option is an option on the Consent Recorder. However, for the implicit option, nothing is being recorded, so it is not clear what it means for the Consent Recorder to support the Implicit Option. 

### Describe the solution you'd like

Remove the Implicit Option from the Consent Recorder. 

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
remove from Consent Recorder

**Comment by JohnMoehrke** [comment]
make clear 108 is only required by the decider when it has explicit option support.
